# Error

```
에러는 호출자 방향으로 전파된다.
```

### 필요성 
- 에러를 처리하지 않으면 프로그램은 강제 종료된다.
``` javascript
foo(); // ReferenceError
console.log(1); //실행 x
```

### try...catch...finally문
try 실행후 에러 발생시 에러를 catch문의 변수에 전달한다.
``` javascript
try {
  foo();
} catch (err) {
  console.error(err); // ReferenceError
} finally {
  console.log('에러발생과 상관없이 무조건 한 번 실행');
}
```

### Error 객체
- message 프로퍼티 + stack 프로퍼티(에러를 발생시킨 콜스택의 호출정보를 나타내는 문자열)

### throw 문
``` javascript
try {
  // 에러를 catch문에 던짐
  throw new Error('error!');
} catch (err) {
  console.error(err)
}
```

